### ISSUE TITLE
Additional analysis

### ISSUE THREAD

**Issue by flosh95** [CharbelSakr15/Jack-Rose#5]
We could add an additional analysis to the bivariate statistics for two categorical variables (iii). For example we can analyse how the survival rate is distributed by class:
print(contingency_coefficient(titanic$Survived, titanic$Pclass))

Additionally we could add an analysis to the bivariate statistics for a binary and a numeric variable (iv). For example we can analyse how the survival rate is distributed by fare:
print(point_biserial_correlation(titanic$Survived, titanic$Fare))

What do you guys think?

**Comment by lepremiere** [comment]
Great idea!! Let's see if not only demographics are correlated with the survival rate but also social status aka money.
I bet back then it made an even bigger difference.

**Comment by mrsalimx** [comment]
All right guys I am going to add the code.

**Comment by CharbelSakr15** [comment]
In the analyze_data document, there seems to be an issue with the point_biserial_correlation function. When attempting to compute the point-biserial correlation using the function with the titanic$Survived and titanic$Fare variables "print(point_biserial_correlation(titanic$Survived, titanic$Fare))", a warning message is generated, and the result obtained is NaN, which is unexpected. We should solve it, right?

**Comment by lepremiere** [comment]
Issue was resolved and analyses added.
Closing thread.
