### ISSUE TITLE
Renaming Documents

### ISSUE THREAD

**Issue by flosh95** [CharbelSakr15/Jack-Rose#6]
As you renamed the documents, please also change the sourcing in "analyze_data.R" and "Funktionen-R-Skript 1.R".

**Comment by lepremiere** [comment]
And we forgot to include the necessary libraries in "analyze_data.R" while merging lately  ( Flosh95 dev #4 ).
We need "ggplot2" and "ggalluvial".

**Comment by mrsalimx** [comment]
Yes I also agree, I've changed the sourcing in "analyze_data.R" and "Funktionen-R-Skript 1.R".

**Comment by lepremiere** [comment]
Issue was resolved.
Closing thread.
